version: "2"

services:
  web:
    build: .
    container_name: u2-app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    env_file:
      ./.env
    depends_on:
      - db
    ports:
      - '80:3000'
    volumes:
      - .:/app
      # - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    container_name: u2-db
    restart: always
    env_file:
      ./.env
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: u2-phpmyadmin
    restart: always
    env_file:
      ./.env
    depends_on:
      - db
    ports:
      - '8080:80'
    volumes:
      - /sessions

volumes:
    db-data:
      driver: local
    # bundle:
    #   driver: local